apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: flowlet-security
spec:
  provider:
    vault:
      server: "http://vault.flowlet-security.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "flowlet-app"
          serviceAccountRef:
            name: vault-auth
            namespace: flowlet-security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: flowlet-security
