#!/bin/bash

# Generate a .env file with strong random secrets for local development

set -euo pipefail

TARGET="$(dirname "$0")/../docker/.env"

if [ -f "$TARGET" ]; then
    echo "⚠️  $TARGET already exists. Overwrite? (y/N)"
    read -r answer
    [ "$answer" != "y" ] && { echo "Aborted."; exit 0; }
fi

gen() { openssl rand -base64 32 | tr -d '/+=\n' | head -c 40; }

cat > "$TARGET" << EOF
# Auto-generated by generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file to version control.

POSTGRES_USER=flowlet
POSTGRES_PASSWORD=$(gen)
POSTGRES_DB=flowlet

REDIS_PASSWORD=$(gen)

JWT_SECRET=$(gen)
SECRET_KEY=$(gen)

GRAFANA_ADMIN_USER=admin
GRAFANA_PASSWORD=$(gen)

VITE_API_BASE_URL=http://localhost:8000

STRIPE_API_KEY=sk_test_REPLACE_ME
PLAID_CLIENT_ID=REPLACE_ME
PLAID_SECRET=REPLACE_ME

ENVIRONMENT=development
LOG_LEVEL=INFO
CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:80

IMAGE_TAG=latest
REGISTRY=flowlet
EOF

echo "✅ Generated $TARGET"
echo "📋 Edit STRIPE_API_KEY, PLAID_CLIENT_ID, PLAID_SECRET with real values before running."
